name: Find Old Branches

on:
  workflow_dispatch:

jobs:
  find-old-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git fetch --all

      - name: Find Old Branches
        run: |
          now=$(date +%s)
          file="old_branches.txt"
          echo "Branches older than 30 days:" > $file
          for branch in $(git branch -r | grep -vE 'master|main|develop' | sed 's/origin\///'); do
            last_commit_date=$(git log -1 --format=%ct origin/$branch)
            age_days=$(( (now - last_commit_date) / 86400 ))
            if [ $age_days -gt 30 ]; then
              echo "$branch (Last updated: $age_days days ago)" >> $file
            fi
          done

      - name: Upload Result File
        run: |
          cat old_branches.txt
